[package]
name = "whist"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
itertools = "0.14"
thiserror = "2"

[dev-dependencies]
tokio = {version = "1.48.0", features = ["full"]}

[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
# future_not_send = {level = "allow", priority = -1}
