[package]
name = "whist-point-calc"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
itertools = "0.14"
thiserror = "2"

[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
